//! Generated by `codegen_payloads`, do not edit by hand.

use serde::Serialize;

use crate::types::{InlineQueryResult, SentWebAppMessage};

impl_payload! {
    @[multipart = result]
    @[validate = crate::requests::validation::validate_answer_web_app_query]
    /// Use this method to set the result of an interaction with a [Web App] and send a corresponding message on behalf of the user to the chat from which the query originated.
    ///
    /// [Web App]: https://core.telegram.org/bots/webapps
    #[derive(Debug, Clone, Serialize)]
    pub AnswerWebAppQuery (AnswerWebAppQuerySetters) => SentWebAppMessage {
        required {
            /// Unique identifier for the query to be answered
            pub web_app_query_id: String [into],
            /// A JSON-serialized object describing the message to be sent
            pub result: InlineQueryResult,
        }
    }
}

impl crate::outbound::OutboundPayload for AnswerWebAppQuery {
    fn outbound_hint(&self) -> crate::outbound::OutboundHint {
        crate::outbound::OutboundHint {
            scope: crate::outbound::OutboundScope::Global,
            class: crate::outbound::OutboundClass::new(crate::outbound::class::OTHER),
            priority: crate::outbound::OutboundPriority::NORMAL,
            weight: std::num::NonZeroU32::new(1).unwrap(),
        }
    }
}
