//! Generated by `codegen_payloads`, do not edit by hand.

use serde::Serialize;

use crate::types::{ChatJoinRequestQueryResult, True};

impl_payload! {
    /// Use this method to process a received chat join request query. Returns _True_ on success.
    #[derive(Debug, PartialEq, Eq, Hash, Clone, Serialize)]
    pub AnswerChatJoinRequestQuery (AnswerChatJoinRequestQuerySetters) => True {
        required {
            /// Unique identifier of the join request query
            pub chat_join_request_query_id: String [into],
            /// Result of the query: approve, decline, or queue
            pub result: ChatJoinRequestQueryResult,
        }
    }
}

impl crate::outbound::OutboundPayload for AnswerChatJoinRequestQuery {
    fn outbound_hint(&self) -> crate::outbound::OutboundHint {
        crate::outbound::OutboundHint {
            scope: crate::outbound::OutboundScope::Global,
            class: crate::outbound::OutboundClass::new(crate::outbound::class::OTHER),
            priority: crate::outbound::OutboundPriority::NORMAL,
            weight: std::num::NonZeroU32::new(1).unwrap(),
        }
    }
}
