//! Generated by `codegen_payloads`, do not edit by hand.

use serde::Serialize;

use crate::types::True;

impl_payload! {
    /// Use this method to remove webhook integration if you decide to switch back to [`GetUpdates`]. Returns True on success. Requires no parameters.
    ///
    /// [`GetUpdates`]: crate::payloads::GetUpdates
    #[derive(Debug, PartialEq, Eq, Hash, Default, Clone, Serialize)]
    pub DeleteWebhook (DeleteWebhookSetters) => True {
        optional {
            /// Pass _True_ to drop all pending updates
            pub drop_pending_updates: bool,
        }
    }
}

impl crate::outbound::OutboundPayload for DeleteWebhook {
    fn outbound_hint(&self) -> crate::outbound::OutboundHint {
        crate::outbound::OutboundHint {
            scope: crate::outbound::OutboundScope::Global,
            class: crate::outbound::OutboundClass::new(crate::outbound::class::MESSAGE_MUTATION),
            priority: crate::outbound::OutboundPriority::NORMAL,
            weight: std::num::NonZeroU32::new(1).unwrap(),
        }
    }
}
