//! Generated by `codegen_payloads`, do not edit by hand.

use serde::Serialize;

use crate::types::True;

impl_payload! {
    /// Use this method to delete a sticker from a set created by the bot. Returns _True_ on success.
    #[derive(Debug, PartialEq, Eq, Hash, Clone, Serialize)]
    pub DeleteStickerFromSet (DeleteStickerFromSetSetters) => True {
        required {
            /// File identifier of the sticker
            pub sticker: String [into],
        }
    }
}

impl crate::outbound::OutboundPayload for DeleteStickerFromSet {
    fn outbound_hint(&self) -> crate::outbound::OutboundHint {
        crate::outbound::OutboundHint {
            scope: crate::outbound::OutboundScope::Global,
            class: crate::outbound::OutboundClass::new(crate::outbound::class::MESSAGE_MUTATION),
            priority: crate::outbound::OutboundPriority::NORMAL,
            weight: std::num::NonZeroU32::new(1).unwrap(),
        }
    }
}
