//! Generated by `codegen_payloads`, do not edit by hand.

use serde::Serialize;

use crate::types::{BusinessConnectionId, StoryId, True};

impl_payload! {
    /// Deletes a story previously posted by the bot on behalf of a managed business account. Requires the _can_manage_stories_ business bot right. Returns _true_ on success.
    #[derive(Debug, PartialEq, Eq, Hash, Clone, Serialize)]
    pub DeleteStory (DeleteStorySetters) => True {
        required {
            /// Unique identifier of the business connection
            pub business_connection_id: BusinessConnectionId,
            /// Unique identifier of the story to delete
            pub story_id: StoryId,
        }
    }
}

impl crate::outbound::OutboundPayload for DeleteStory {
    fn outbound_hint(&self) -> crate::outbound::OutboundHint {
        crate::outbound::OutboundHint {
            scope: crate::outbound::OutboundScope::Global,
            class: crate::outbound::OutboundClass::new(crate::outbound::class::MESSAGE_MUTATION),
            priority: crate::outbound::OutboundPriority::NORMAL,
            weight: std::num::NonZeroU32::new(1).unwrap(),
        }
    }
}
