//! Generated by `codegen_payloads`, do not edit by hand.

use serde::Serialize;

use crate::types::{BusinessConnectionId, ChatId, InputChecklist, Message, MessageId, ReplyMarkup};

impl_payload! {
    /// Use this method to edit a checklist on behalf of a connected business account. On success, the edited [`Message`] is returned.
    ///
    /// [`Message`]: crate::types::Message
    #[derive(Debug, PartialEq, Eq, Hash, Clone, Serialize)]
    pub EditMessageChecklist (EditMessageChecklistSetters) => Message {
        required {
            /// Unique identifier of the business connection on behalf of which the message will be sent
            pub business_connection_id: BusinessConnectionId,
            /// Unique identifier for the target chat
            pub chat_id: ChatId [into],
            /// Unique identifier for the target message
            #[serde(flatten)]
            pub message_id: MessageId,
            /// The new checklist
            pub checklist: InputChecklist,
        }
        optional {
            /// The new inline keyboard for the message
            pub reply_markup: ReplyMarkup [into],
        }
    }
}

impl crate::outbound::OutboundPayload for EditMessageChecklist {
    fn outbound_hint(&self) -> crate::outbound::OutboundHint {
        crate::outbound::OutboundHint {
            scope: crate::outbound::classify::chat_id_scope(self.chat_id),
            class: crate::outbound::OutboundClass::new(crate::outbound::class::MESSAGE_MUTATION),
            priority: crate::outbound::OutboundPriority::NORMAL,
            weight: std::num::NonZeroU32::new(1).unwrap(),
        }
    }
}
