//! Generated by `codegen_payloads`, do not edit by hand.

use serde::Serialize;

use crate::types::{
    InlineKeyboardMarkup, InputRichMessage, LinkPreviewOptions, MessageEntity, ParseMode,
    Recipient, True, UserId,
};

impl_payload! {
    @[validate = crate::requests::validation::validate_edit_ephemeral_message_text]
    /// Use this method to edit an ephemeral text or rich message. Returns _True_ on success.
    #[derive(Debug, Clone, Serialize)]
    pub EditEphemeralMessageText (EditEphemeralMessageTextSetters) => True {
        required {
            /// Unique identifier for the target chat or username of the target supergroup
            pub chat_id: Recipient [into],
            /// Identifier of the user who received the message
            pub receiver_user_id: UserId,
            /// Identifier of the ephemeral message to edit
            pub ephemeral_message_id: i32,
        }
        optional {
            /// New text of the message, 1-4096 characters after entity parsing; required if rich_message isn't specified
            pub text: String [into],
            /// New rich message content
            pub rich_message: InputRichMessage,
            /// Mode for parsing entities in the message text
            pub parse_mode: ParseMode,
            /// List of special entities that appear in message text
            pub entities: Vec<MessageEntity> [collect],
            /// Link preview generation options for the message
            pub link_preview_options: LinkPreviewOptions,
            /// Inline keyboard for the message
            pub reply_markup: InlineKeyboardMarkup,
        }
    }
}

impl crate::outbound::OutboundPayload for EditEphemeralMessageText {
    fn outbound_hint(&self) -> crate::outbound::OutboundHint {
        crate::outbound::OutboundHint {
            scope: crate::outbound::classify::scope_of_recipient(&self.chat_id),
            class: crate::outbound::OutboundClass::new(crate::outbound::class::MESSAGE_MUTATION),
            priority: crate::outbound::OutboundPriority::NORMAL,
            weight: std::num::NonZeroU32::new(1).unwrap(),
        }
    }
}
