//! Generated by `codegen_payloads`, do not edit by hand.

use serde::Serialize;

use crate::types::{InlineKeyboardMarkup, Recipient, True, UserId};

impl_payload! {
    /// Use this method to edit only the reply markup of an ephemeral message. Returns _True_ on success.
    #[derive(Debug, PartialEq, Eq, Hash, Clone, Serialize)]
    pub EditEphemeralMessageReplyMarkup (EditEphemeralMessageReplyMarkupSetters) => True {
        required {
            /// Unique identifier for the target chat or username of the target supergroup
            pub chat_id: Recipient [into],
            /// Identifier of the user who received the message
            pub receiver_user_id: UserId,
            /// Identifier of the ephemeral message to edit
            pub ephemeral_message_id: i32,
        }
        optional {
            /// Inline keyboard for the message
            pub reply_markup: InlineKeyboardMarkup,
        }
    }
}
