//! Generated by `codegen_payloads`, do not edit by hand.

use serde::Serialize;

use crate::types::{InlineKeyboardMarkup, InputMedia, Recipient, True, UserId};

impl_payload! {
    /// Use this method to edit the media of an ephemeral message. New files can't be uploaded. Returns _True_ on success.
    #[derive(Debug, Clone, Serialize)]
    pub EditEphemeralMessageMedia (EditEphemeralMessageMediaSetters) => True {
        required {
            /// Unique identifier for the target chat or username of the target supergroup
            pub chat_id: Recipient [into],
            /// Identifier of the user who received the message
            pub receiver_user_id: UserId,
            /// Identifier of the ephemeral message to edit
            pub ephemeral_message_id: i32,
            /// New media content; use a file_id or URL because direct upload isn't supported
            pub media: InputMedia,
        }
        optional {
            /// Inline keyboard for the message
            pub reply_markup: InlineKeyboardMarkup,
        }
    }
}

impl crate::outbound::OutboundPayload for EditEphemeralMessageMedia {
    fn outbound_hint(&self) -> crate::outbound::OutboundHint {
        crate::outbound::OutboundHint {
            scope: crate::outbound::classify::scope_of_recipient(&self.chat_id),
            class: crate::outbound::OutboundClass::new(crate::outbound::class::MESSAGE_MUTATION),
            priority: crate::outbound::OutboundPriority::NORMAL,
            weight: std::num::NonZeroU32::new(1).unwrap(),
        }
    }
}
