//! Generated by `codegen_payloads`, do not edit by hand.

use serde::Serialize;

use crate::types::{InlineKeyboardMarkup, InputMedia, Recipient, True, UserId};

impl_payload! {
    @[multipart = media]
    /// Use this method to edit the media of an ephemeral message. Returns _True_ on success.
    #[derive(Debug, Clone, Serialize)]
    pub EditEphemeralMessageMedia (EditEphemeralMessageMediaSetters) => True {
        required {
            /// Unique identifier for the target chat or username of the target supergroup
            pub chat_id: Recipient [into],
            /// Identifier of the user who received the message
            pub receiver_user_id: UserId,
            /// Identifier of the ephemeral message to edit
            pub ephemeral_message_id: i32,
            /// New media content
            pub media: InputMedia,
        }
        optional {
            /// Inline keyboard for the message
            pub reply_markup: InlineKeyboardMarkup,
        }
    }
}
