//! Generated by `codegen_payloads`, do not edit by hand.

use serde::Serialize;

use crate::types::{InlineKeyboardMarkup, MessageEntity, ParseMode, Recipient, True, UserId};

impl_payload! {
    /// Use this method to edit the caption of an ephemeral message. Returns _True_ on success.
    #[derive(Debug, PartialEq, Eq, Hash, Clone, Serialize)]
    pub EditEphemeralMessageCaption (EditEphemeralMessageCaptionSetters) => True {
        required {
            /// Unique identifier for the target chat or username of the target supergroup
            pub chat_id: Recipient [into],
            /// Identifier of the user who received the message
            pub receiver_user_id: UserId,
            /// Identifier of the ephemeral message to edit
            pub ephemeral_message_id: i32,
        }
        optional {
            /// New caption of the message, 0-1024 characters after entity parsing
            pub caption: String [into],
            /// Mode for parsing entities in the caption
            pub parse_mode: ParseMode,
            /// List of special entities that appear in the caption
            pub caption_entities: Vec<MessageEntity> [collect],
            /// Inline keyboard for the message
            pub reply_markup: InlineKeyboardMarkup,
        }
    }
}

impl crate::outbound::OutboundPayload for EditEphemeralMessageCaption {
    fn outbound_hint(&self) -> crate::outbound::OutboundHint {
        crate::outbound::OutboundHint {
            scope: crate::outbound::classify::scope_of_recipient(&self.chat_id),
            class: crate::outbound::OutboundClass::new(crate::outbound::class::MESSAGE_MUTATION),
            priority: crate::outbound::OutboundPriority::NORMAL,
            weight: std::num::NonZeroU32::new(1).unwrap(),
        }
    }
}
