//! Generated by `codegen_payloads`, do not edit by hand.

use serde::Serialize;

use crate::types::{Message, UserId};

impl_payload! {
    /// Use this method to get the last messages from the personal chat of a given user. On success, an array of [`Message`] objects is returned.
    ///
    /// [`Message`]: crate::types::Message
    #[derive(Debug, PartialEq, Eq, Hash, Clone, Serialize)]
    pub GetUserPersonalChatMessages (GetUserPersonalChatMessagesSetters) => Vec<Message> {
        required {
            /// Unique identifier for the target user
            pub user_id: UserId,
            /// The maximum number of messages to return
            pub limit: u8,
        }
    }
}

impl crate::outbound::OutboundPayload for GetUserPersonalChatMessages {
    fn outbound_hint(&self) -> crate::outbound::OutboundHint {
        crate::outbound::OutboundHint {
            scope: crate::outbound::classify::user_id_scope(self.user_id),
            class: crate::outbound::OutboundClass::new(crate::outbound::class::READ),
            priority: crate::outbound::OutboundPriority::NORMAL,
            weight: std::num::NonZeroU32::new(1).unwrap(),
        }
    }
}
