//! Generated by `codegen_payloads`, do not edit by hand.

use serde::Serialize;

use crate::types::{ChatMember, Recipient};

impl_payload! {
    /// Use this method to get a list of administrators in a chat. On success, returns an Array of [`ChatMember`] objects that contains information about all chat administrators except other bots. If the chat is a group or a supergroup and no administrators were appointed, only the creator will be returned.
    ///
    /// [`ChatMember`]: crate::types::ChatMember
    #[derive(Debug, PartialEq, Eq, Hash, Clone, Serialize)]
    pub GetChatAdministrators (GetChatAdministratorsSetters) => Vec<ChatMember> {
        required {
            /// Unique identifier for the target chat or username of the target channel (in the format `@channelusername`)
            pub chat_id: Recipient [into],
        }
        optional {
            /// Pass True to additionally receive all bots that are administrators of the chat; other bots are omitted by default
            pub return_bots: bool,
        }
    }
}

impl crate::outbound::OutboundPayload for GetChatAdministrators {
    fn outbound_hint(&self) -> crate::outbound::OutboundHint {
        crate::outbound::OutboundHint {
            scope: crate::outbound::classify::scope_of_recipient(&self.chat_id),
            class: crate::outbound::OutboundClass::new(crate::outbound::class::READ),
            priority: crate::outbound::OutboundPriority::NORMAL,
            weight: std::num::NonZeroU32::new(1).unwrap(),
        }
    }
}
