//! Generated by `codegen_payloads`, do not edit by hand.

use serde::Serialize;

use crate::types::{BusinessConnection, BusinessConnectionId};

impl_payload! {
    /// Use this method to get information about the connection of the bot with a business account. Returns a BusinessConnection object on success.
    #[derive(Debug, PartialEq, Eq, Hash, Clone, Serialize)]
    pub GetBusinessConnection (GetBusinessConnectionSetters) => BusinessConnection {
        required {
            /// Unique identifier of the business connection
            pub business_connection_id: BusinessConnectionId,
        }
    }
}

impl crate::outbound::OutboundPayload for GetBusinessConnection {
    fn outbound_hint(&self) -> crate::outbound::OutboundHint {
        crate::outbound::OutboundHint {
            scope: crate::outbound::OutboundScope::Global,
            class: crate::outbound::OutboundClass::new(crate::outbound::class::READ),
            priority: crate::outbound::OutboundPriority::NORMAL,
            weight: std::num::NonZeroU32::new(1).unwrap(),
        }
    }
}
