//! Generated by `codegen_payloads`, do not edit by hand.

use serde::Serialize;

use crate::types::{UserId, UserProfileAudios};

impl_payload! {
    /// Use this method to get a list of profile audios for a user. Returns a [`UserProfileAudios`] object.
    ///
    /// [`UserProfileAudios`]: crate::types::UserProfileAudios
    #[derive(Debug, PartialEq, Eq, Hash, Clone, Serialize)]
    pub GetUserProfileAudios (GetUserProfileAudiosSetters) => UserProfileAudios {
        required {
            /// Unique identifier of the target user
            pub user_id: UserId,
        }
        optional {
            /// Sequential number of the first audio to be returned
            pub offset: u32,
            /// Limits the number of audios to be retrieved
            pub limit: u8,
        }
    }
}

impl crate::outbound::OutboundPayload for GetUserProfileAudios {
    fn outbound_hint(&self) -> crate::outbound::OutboundHint {
        crate::outbound::OutboundHint {
            scope: crate::outbound::classify::user_id_scope(self.user_id),
            class: crate::outbound::OutboundClass::new(crate::outbound::class::READ),
            priority: crate::outbound::OutboundPriority::NORMAL,
            weight: std::num::NonZeroU32::new(1).unwrap(),
        }
    }
}
