//! Generated by `codegen_payloads`, do not edit by hand.

use serde::Serialize;

use crate::types::Gifts;

impl_payload! {
    /// Returns the list of gifts that can be sent by the bot to users. Requires no parameters. Returns a [`Gifts`] object.
    ///
    /// [`Gifts`]: crate::types::Gifts
    #[derive(Debug, PartialEq, Eq, Hash, Default, Clone, Serialize)]
    pub GetAvailableGifts (GetAvailableGiftsSetters) => Gifts {

    }
}

impl crate::outbound::OutboundPayload for GetAvailableGifts {
    fn outbound_hint(&self) -> crate::outbound::OutboundHint {
        crate::outbound::OutboundHint {
            scope: crate::outbound::OutboundScope::Global,
            class: crate::outbound::OutboundClass::new(crate::outbound::class::READ),
            priority: crate::outbound::OutboundPriority::NORMAL,
            weight: std::num::NonZeroU32::new(1).unwrap(),
        }
    }
}
