//! Generated by `codegen_payloads`, do not edit by hand.

use serde::Serialize;

use crate::types::BotShortDescription;

impl_payload! {
    /// Use this method to get the current bot short description for the given user language. Returns [`BotShortDescription`] on success.
    ///
    /// [`BotShortDescription`]: crate::types::BotShortDescription
    #[derive(Debug, PartialEq, Eq, Hash, Default, Clone, Serialize)]
    pub GetMyShortDescription (GetMyShortDescriptionSetters) => BotShortDescription {
        optional {
            /// A two-letter ISO 639-1 language code
            pub language_code: String [into],
        }
    }
}

impl crate::outbound::OutboundPayload for GetMyShortDescription {
    fn outbound_hint(&self) -> crate::outbound::OutboundHint {
        crate::outbound::OutboundHint {
            scope: crate::outbound::OutboundScope::Global,
            class: crate::outbound::OutboundClass::new(crate::outbound::class::READ),
            priority: crate::outbound::OutboundPriority::NORMAL,
            weight: std::num::NonZeroU32::new(1).unwrap(),
        }
    }
}
