//! Generated by `codegen_payloads`, do not edit by hand.

use serde::Serialize;

use crate::types::Sticker;

impl_payload! {
    /// Use this method to get custom emoji stickers, which can be used as a forum topic icon by any user. Requires no parameters. Returns an Array of `Sticker` objects.
    #[derive(Debug, PartialEq, Eq, Hash, Default, Clone, Serialize)]
    pub GetForumTopicIconStickers (GetForumTopicIconStickersSetters) => Vec<Sticker> {

    }
}

impl crate::outbound::OutboundPayload for GetForumTopicIconStickers {
    fn outbound_hint(&self) -> crate::outbound::OutboundHint {
        crate::outbound::OutboundHint {
            scope: crate::outbound::OutboundScope::Global,
            class: crate::outbound::OutboundClass::new(crate::outbound::class::READ),
            priority: crate::outbound::OutboundPriority::NORMAL,
            weight: std::num::NonZeroU32::new(1).unwrap(),
        }
    }
}
