//! Generated by `codegen_payloads`, do not edit by hand.

use serde::Serialize;

use crate::types::BotDescription;

impl_payload! {
    /// Use this method to get the current bot description for the given user language. Returns [`BotDescription`] on success.
    ///
    /// [`BotDescription`]: crate::types::BotDescription
    #[derive(Debug, PartialEq, Eq, Hash, Default, Clone, Serialize)]
    pub GetMyDescription (GetMyDescriptionSetters) => BotDescription {
        optional {
            /// A two-letter ISO 639-1 language code
            pub language_code: String [into],
        }
    }
}

impl crate::outbound::OutboundPayload for GetMyDescription {
    fn outbound_hint(&self) -> crate::outbound::OutboundHint {
        crate::outbound::OutboundHint {
            scope: crate::outbound::OutboundScope::Global,
            class: crate::outbound::OutboundClass::new(crate::outbound::class::READ),
            priority: crate::outbound::OutboundPriority::NORMAL,
            weight: std::num::NonZeroU32::new(1).unwrap(),
        }
    }
}
