//! Generated by `codegen_payloads`, do not edit by hand.

use serde::Serialize;

use crate::types::BotName;

impl_payload! {
    /// Use this method to get the current bot name for the given user language. Returns [`BotName`] on success.
    ///
    /// [`BotName`]: crate::types::BotName
    #[derive(Debug, PartialEq, Eq, Hash, Default, Clone, Serialize)]
    pub GetMyName (GetMyNameSetters) => BotName {
        optional {
            /// A two-letter ISO 639-1 language code or an empty string
            pub language_code: String [into],
        }
    }
}

impl crate::outbound::OutboundPayload for GetMyName {
    fn outbound_hint(&self) -> crate::outbound::OutboundHint {
        crate::outbound::OutboundHint {
            scope: crate::outbound::OutboundScope::Global,
            class: crate::outbound::OutboundClass::new(crate::outbound::class::READ),
            priority: crate::outbound::OutboundPriority::NORMAL,
            weight: std::num::NonZeroU32::new(1).unwrap(),
        }
    }
}
