//! Generated by `codegen_payloads`, do not edit by hand.

use serde::Serialize;

use crate::types::{Recipient, UserChatBoosts, UserId};

impl_payload! {
    /// Use this method to get the list of boosts added to a chat by a user. Requires administrator rights in the chat. Returns a [`UserChatBoosts`] object.
    ///
    /// [`UserChatBoosts`]: crate::types::UserChatBoosts
    #[derive(Debug, PartialEq, Eq, Hash, Clone, Serialize)]
    pub GetUserChatBoosts (GetUserChatBoostsSetters) => UserChatBoosts {
        required {
            /// Unique identifier for the chat or username of the channel (in the format @channelusername)
            pub chat_id: Recipient [into],
            /// Unique identifier of the target user
            pub user_id: UserId,
        }
    }
}

impl crate::outbound::OutboundPayload for GetUserChatBoosts {
    fn outbound_hint(&self) -> crate::outbound::OutboundHint {
        crate::outbound::OutboundHint {
            scope: crate::outbound::classify::scope_of_recipient(&self.chat_id),
            class: crate::outbound::OutboundClass::new(crate::outbound::class::READ),
            priority: crate::outbound::OutboundPriority::NORMAL,
            weight: std::num::NonZeroU32::new(1).unwrap(),
        }
    }
}
