//! Generated by `codegen_payloads`, do not edit by hand.

use serde::Serialize;

use crate::types::{CustomEmojiId, Sticker};

impl_payload! {
    /// Use this method to get information about custom emoji stickers by their identifiers. Returns an Array of Sticker objects.
    #[derive(Debug, PartialEq, Eq, Hash, Clone, Serialize)]
    pub GetCustomEmojiStickers (GetCustomEmojiStickersSetters) => Vec<Sticker> {
        required {
            /// List of custom emoji identifiers. At most 200 custom emoji identifiers can be specified.
            pub custom_emoji_ids: Vec<CustomEmojiId> [collect],
        }
    }
}

impl crate::outbound::OutboundPayload for GetCustomEmojiStickers {
    fn outbound_hint(&self) -> crate::outbound::OutboundHint {
        crate::outbound::OutboundHint {
            scope: crate::outbound::OutboundScope::Global,
            class: crate::outbound::OutboundClass::new(crate::outbound::class::READ),
            priority: crate::outbound::OutboundPriority::NORMAL,
            weight: std::num::NonZeroU32::new(1).unwrap(),
        }
    }
}
