//! Generated by `codegen_payloads`, do not edit by hand.

use serde::Serialize;

use crate::types::{ChatMember, Recipient, UserId};

impl_payload! {
    /// Use this method to get information about a member of a chat. Returns a [`ChatMember`] object on success.
    ///
    /// [`ChatMember`]: crate::types::ChatMember
    #[derive(Debug, PartialEq, Eq, Hash, Clone, Serialize)]
    pub GetChatMember (GetChatMemberSetters) => ChatMember {
        required {
            /// Unique identifier for the target chat or username of the target channel (in the format `@channelusername`)
            pub chat_id: Recipient [into],
            /// Unique identifier of the target user
            pub user_id: UserId,
        }
    }
}

impl crate::outbound::OutboundPayload for GetChatMember {
    fn outbound_hint(&self) -> crate::outbound::OutboundHint {
        crate::outbound::OutboundHint {
            scope: crate::outbound::classify::scope_of_recipient(&self.chat_id),
            class: crate::outbound::OutboundClass::new(crate::outbound::class::READ),
            priority: crate::outbound::OutboundPriority::NORMAL,
            weight: std::num::NonZeroU32::new(1).unwrap(),
        }
    }
}
