//! Generated by `codegen_payloads`, do not edit by hand.

use serde::Serialize;

use crate::types::{BotAccessSettings, UserId};

impl_payload! {
    /// Use this method to get the access settings of a managed bot. Returns a [`BotAccessSettings`] object on success.
    ///
    /// [`BotAccessSettings`]: crate::types::BotAccessSettings
    #[derive(Debug, PartialEq, Eq, Hash, Clone, Serialize)]
    pub GetManagedBotAccessSettings (GetManagedBotAccessSettingsSetters) => BotAccessSettings {
        required {
            /// User identifier of the managed bot whose access settings will be returned
            pub user_id: UserId,
        }
    }
}

impl crate::outbound::OutboundPayload for GetManagedBotAccessSettings {
    fn outbound_hint(&self) -> crate::outbound::OutboundHint {
        crate::outbound::OutboundHint {
            scope: crate::outbound::classify::user_id_scope(self.user_id),
            class: crate::outbound::OutboundClass::new(crate::outbound::class::READ),
            priority: crate::outbound::OutboundPriority::NORMAL,
            weight: std::num::NonZeroU32::new(1).unwrap(),
        }
    }
}
