//! Generated by `codegen_payloads`, do not edit by hand.

use serde::Serialize;

use crate::types::StickerSet;

impl_payload! {
    /// Use this method to get a sticker set. On success, a StickerSet object is returned.
    #[derive(Debug, PartialEq, Eq, Hash, Clone, Serialize)]
    pub GetStickerSet (GetStickerSetSetters) => StickerSet {
        required {
            /// Name of the sticker set
            pub name: String [into],
        }
    }
}

impl crate::outbound::OutboundPayload for GetStickerSet {
    fn outbound_hint(&self) -> crate::outbound::OutboundHint {
        crate::outbound::OutboundHint {
            scope: crate::outbound::OutboundScope::Global,
            class: crate::outbound::OutboundClass::new(crate::outbound::class::READ),
            priority: crate::outbound::OutboundPriority::NORMAL,
            weight: std::num::NonZeroU32::new(1).unwrap(),
        }
    }
}
