//! Generated by `codegen_payloads`, do not edit by hand.

use serde::Serialize;

use crate::types::Recipient;

impl_payload! {
    /// Use this method to get the number of members in a chat. Returns _Int_ on success.
    #[derive(Debug, PartialEq, Eq, Hash, Clone, Serialize)]
    pub GetChatMembersCount (GetChatMembersCountSetters) => u32 {
        required {
            /// Unique identifier for the target chat or username of the target channel (in the format `@channelusername`)
            pub chat_id: Recipient [into],
        }
    }
}

impl crate::outbound::OutboundPayload for GetChatMembersCount {
    fn outbound_hint(&self) -> crate::outbound::OutboundHint {
        crate::outbound::OutboundHint {
            scope: crate::outbound::classify::scope_of_recipient(&self.chat_id),
            class: crate::outbound::OutboundClass::new(crate::outbound::class::READ),
            priority: crate::outbound::OutboundPriority::NORMAL,
            weight: std::num::NonZeroU32::new(1).unwrap(),
        }
    }
}
