//! Generated by `codegen_payloads`, do not edit by hand.

use serde::Serialize;

use crate::types::{True, UserId};

impl_payload! {
    /// Removes verification from a user who is currently verified [on behalf of the organization] represented by the bot. Returns _true_ on success.
    ///
    /// [on behalf of the organization]: https://telegram.org/verify#third-party-verification
    #[derive(Debug, PartialEq, Eq, Hash, Clone, Serialize)]
    pub RemoveUserVerification (RemoveUserVerificationSetters) => True {
        required {
            /// Unique identifier of the target user
            pub user_id: UserId,
        }
    }
}

impl crate::outbound::OutboundPayload for RemoveUserVerification {
    fn outbound_hint(&self) -> crate::outbound::OutboundHint {
        crate::outbound::OutboundHint {
            scope: crate::outbound::classify::user_id_scope(self.user_id),
            class: crate::outbound::OutboundClass::new(crate::outbound::class::OTHER),
            priority: crate::outbound::OutboundPriority::NORMAL,
            weight: std::num::NonZeroU32::new(1).unwrap(),
        }
    }
}
