//! Generated by `codegen_payloads`, do not edit by hand.

use serde::Serialize;

use crate::types::{Recipient, True};

impl_payload! {
    /// Removes verification from a chat that is currently verified [on behalf of the organization] represented by the bot. Returns _true_ on success.
    ///
    /// [on behalf of the organization]: https://telegram.org/verify#third-party-verification
    #[derive(Debug, PartialEq, Eq, Hash, Clone, Serialize)]
    pub RemoveChatVerification (RemoveChatVerificationSetters) => True {
        required {
            /// Unique identifier for the target chat or username of the target channel
            pub chat_id: Recipient [into],
        }
    }
}

impl crate::outbound::OutboundPayload for RemoveChatVerification {
    fn outbound_hint(&self) -> crate::outbound::OutboundHint {
        crate::outbound::OutboundHint {
            scope: crate::outbound::classify::scope_of_recipient(&self.chat_id),
            class: crate::outbound::OutboundClass::new(crate::outbound::class::OTHER),
            priority: crate::outbound::OutboundPriority::NORMAL,
            weight: std::num::NonZeroU32::new(1).unwrap(),
        }
    }
}
