//! Generated by `codegen_payloads`, do not edit by hand.

use serde::Serialize;

use crate::types::{MessageEntity, ParseMode, ThreadId, True, UserId};

impl_payload! {
    /// Use this method to stream a partial message to a user while the message is being generated. Returns _True_ on success.
    #[derive(Debug, PartialEq, Eq, Hash, Clone, Serialize)]
    pub SendMessageDraft (SendMessageDraftSetters) => True {
        required {
            /// Unique identifier for the target private chat
            pub chat_id: UserId,
            /// Unique identifier of the message draft; must be non-zero
            pub draft_id: i32,
        }
        optional {
            /// Unique identifier for the target message thread
            pub message_thread_id: ThreadId,
            /// Text of the message to be sent
            pub text: String [into],
            /// Mode for parsing entities in the message text
            pub parse_mode: ParseMode,
            /// List of special entities that appear in message text
            pub entities: Vec<MessageEntity> [collect],
            /// Pass True to show the user a button to stop further drafts
            pub can_stop: bool,
            /// Pass True to keep the draft in the chat when the button is pressed
            pub keep_on_stop: bool,
        }
    }
}
