//! Generated by `codegen_payloads`, do not edit by hand.

use serde::Serialize;

use crate::types::{
    BusinessConnectionId, EffectId, InputRichMessage, Message, Recipient, ReplyMarkup,
    ReplyParameters, SuggestedPostParameters, ThreadId, TopicId,
};

impl_payload! {
    @[multipart = rich_message]
    @[validate = crate::requests::validation::validate_send_rich_message]
    /// Use this method to send rich messages. On success, the sent [`Message`] is returned.
    ///
    /// [`Message`]: crate::types::Message
    #[derive(Debug, Clone, Serialize)]
    pub SendRichMessage (SendRichMessageSetters) => Message {
        required {
            /// Unique identifier for the target chat or username
            pub chat_id: Recipient [into],
            /// The message to be sent
            pub rich_message: InputRichMessage,
        }
        optional {
            /// Unique identifier of the business connection on behalf of which the message will be sent
            pub business_connection_id: BusinessConnectionId,
            /// Unique identifier for the target message thread
            pub message_thread_id: ThreadId,
            /// Identifier of the direct messages topic
            pub direct_messages_topic_id: TopicId,
            /// Sends the message silently
            pub disable_notification: bool,
            /// Protects the contents from forwarding and saving
            pub protect_content: bool,
            /// Allows paid high-throughput broadcasting
            pub allow_paid_broadcast: bool,
            /// Message effect identifier
            pub message_effect_id: EffectId,
            /// Parameters of the suggested post
            pub suggested_post_parameters: SuggestedPostParameters,
            /// Description of the message to reply to
            pub reply_parameters: ReplyParameters,
            /// Additional interface options
            pub reply_markup: ReplyMarkup [into],
        }
    }
}
