//! Generated by `codegen_payloads`, do not edit by hand.

use serde::Serialize;
use url::Url;

use crate::types::True;

impl_payload! {
    /// Use this method to process a received chat join request query by showing a Mini App to the user before deciding the outcome. Returns _True_ on success.
    #[derive(Debug, PartialEq, Eq, Hash, Clone, Serialize)]
    pub SendChatJoinRequestWebApp (SendChatJoinRequestWebAppSetters) => True {
        required {
            /// Unique identifier of the join request query
            pub chat_join_request_query_id: String [into],
            /// HTTPS URL of a Web App to be opened
            pub web_app_url: Url,
        }
    }
}

impl crate::outbound::OutboundPayload for SendChatJoinRequestWebApp {
    fn outbound_hint(&self) -> crate::outbound::OutboundHint {
        crate::outbound::OutboundHint {
            scope: crate::outbound::OutboundScope::Global,
            class: crate::outbound::OutboundClass::new(crate::outbound::class::MESSAGE_SEND),
            priority: crate::outbound::OutboundPriority::NORMAL,
            weight: std::num::NonZeroU32::new(1).unwrap(),
        }
    }
}
