//! Generated by `codegen_payloads`, do not edit by hand.

use serde::Serialize;

use crate::types::{InputRichMessage, ThreadId, True, UserId};

impl_payload! {
    @[validate = crate::requests::validation::validate_send_rich_message_draft]
    /// Use this method to stream a partial rich message to a user while it is being generated. Returns _True_ on success.
    #[derive(Debug, Clone, Serialize)]
    pub SendRichMessageDraft (SendRichMessageDraftSetters) => True {
        required {
            /// Unique identifier for the target private chat
            pub chat_id: UserId,
            /// Unique non-zero identifier of the message draft
            pub draft_id: i32,
            /// The partial message to be streamed; direct upload of new files isn't supported
            pub rich_message: InputRichMessage,
        }
        optional {
            /// Unique identifier for the target message thread
            pub message_thread_id: ThreadId,
        }
    }
}

impl crate::outbound::OutboundPayload for SendRichMessageDraft {
    fn outbound_hint(&self) -> crate::outbound::OutboundHint {
        crate::outbound::OutboundHint {
            scope: crate::outbound::classify::draft_chat_id_scope(&self.chat_id),
            class: crate::outbound::OutboundClass::new(crate::outbound::class::MESSAGE_SEND),
            priority: crate::outbound::OutboundPriority::NORMAL,
            weight: std::num::NonZeroU32::new(1).unwrap(),
        }
    }
}
