//! Generated by `codegen_payloads`, do not edit by hand.

use serde::Serialize;

use crate::types::{MessageEntity, ParseMode, ThreadId, True, UserId};

impl_payload! {
    @[validate = crate::requests::validation::validate_send_message_draft]
    /// Use this method to stream a partial message to a user while the message is being generated. Returns _True_ on success.
    #[derive(Debug, PartialEq, Eq, Hash, Clone, Serialize)]
    pub SendMessageDraft (SendMessageDraftSetters) => True {
        required {
            /// Unique identifier for the target private chat
            pub chat_id: UserId,
            /// Unique identifier of the message draft; must be non-zero
            pub draft_id: i32,
        }
        optional {
            /// Unique identifier for the target message thread
            pub message_thread_id: ThreadId,
            /// Text of the message to be sent
            pub text: String [into],
            /// Mode for parsing entities in the message text
            pub parse_mode: ParseMode,
            /// List of special entities that appear in message text
            pub entities: Vec<MessageEntity> [collect],
        }
    }
}

impl crate::outbound::OutboundPayload for SendMessageDraft {
    fn outbound_hint(&self) -> crate::outbound::OutboundHint {
        crate::outbound::OutboundHint {
            scope: crate::outbound::classify::draft_chat_id_scope(&self.chat_id),
            class: crate::outbound::OutboundClass::new(crate::outbound::class::MESSAGE_SEND),
            priority: crate::outbound::OutboundPriority::NORMAL,
            weight: std::num::NonZeroU32::new(1).unwrap(),
        }
    }
}
