//! Generated by `codegen_payloads`, do not edit by hand.

use serde::Serialize;

use crate::types::{InputRichMessage, ThreadId, True, UserId};

impl_payload! {
    /// Use this method to stream a partial rich message to a user while it is being generated. Returns _True_ on success.
    #[derive(Debug, Clone, Serialize)]
    pub SendRichMessageDraft (SendRichMessageDraftSetters) => True {
        required {
            /// Unique identifier for the target private chat
            pub chat_id: UserId,
            /// Unique non-zero identifier of the message draft
            pub draft_id: i32,
            /// The partial message to be streamed; direct upload of new files isn't supported
            pub rich_message: InputRichMessage,
        }
        optional {
            /// Unique identifier for the target message thread
            pub message_thread_id: ThreadId,
        }
    }
}
