//! Generated by `codegen_payloads`, do not edit by hand.

use serde::Serialize;

use crate::types::{ChatId, MenuButton, True};

impl_payload! {
    /// Use this method to change the bot's menu button in a private chat, or the default menu button.
    #[derive(Debug, PartialEq, Eq, Hash, Default, Clone, Serialize)]
    pub SetChatMenuButton (SetChatMenuButtonSetters) => True {
        optional {
            /// Unique identifier for the target private chat. If not specified, default bot's menu button will be changed.
            pub chat_id: ChatId [into],
            /// An object for the new bot's menu button. Defaults to MenuButtonDefault
            pub menu_button: MenuButton,
        }
    }
}

impl crate::outbound::OutboundPayload for SetChatMenuButton {
    fn outbound_hint(&self) -> crate::outbound::OutboundHint {
        crate::outbound::OutboundHint {
            scope: match self.chat_id {
                Some(chat_id) => crate::outbound::classify::chat_id_scope(chat_id),
                None => crate::outbound::OutboundScope::Global,
            },
            class: crate::outbound::OutboundClass::new(crate::outbound::class::OTHER),
            priority: crate::outbound::OutboundPriority::NORMAL,
            weight: std::num::NonZeroU32::new(1).unwrap(),
        }
    }
}
