//! Generated by `codegen_payloads`, do not edit by hand.

use serde::Serialize;

use crate::types::True;

impl_payload! {
    /// Use this method to set the title of a created sticker set. Returns True on success.
    #[derive(Debug, PartialEq, Eq, Hash, Clone, Serialize)]
    pub SetStickerSetTitle (SetStickerSetTitleSetters) => True {
        required {
            /// Sticker set name
            pub name: String [into],
            /// Sticker set title, 1-64 characters
            pub title: String [into],
        }
    }
}

impl crate::outbound::OutboundPayload for SetStickerSetTitle {
    fn outbound_hint(&self) -> crate::outbound::OutboundHint {
        crate::outbound::OutboundHint {
            scope: crate::outbound::OutboundScope::Global,
            class: crate::outbound::OutboundClass::new(crate::outbound::class::OTHER),
            priority: crate::outbound::OutboundPriority::NORMAL,
            weight: std::num::NonZeroU32::new(1).unwrap(),
        }
    }
}
