//! Generated by `codegen_payloads`, do not edit by hand.

use serde::Serialize;

use crate::types::{CustomEmojiId, True};

impl_payload! {
    /// Use this method to set the thumbnail of a custom emoji sticker set. Returns True on success.
    #[derive(Debug, PartialEq, Eq, Hash, Clone, Serialize)]
    pub SetCustomEmojiStickerSetThumbnail (SetCustomEmojiStickerSetThumbnailSetters) => True {
        required {
            /// Sticker set name
            pub name: String [into],
        }
        optional {
            /// Custom emoji identifier of a sticker from the sticker set; pass an empty string to drop the thumbnail and use the first sticker as the thumbnail.
            pub custom_emoji_id: CustomEmojiId,
        }
    }
}

impl crate::outbound::OutboundPayload for SetCustomEmojiStickerSetThumbnail {
    fn outbound_hint(&self) -> crate::outbound::OutboundHint {
        crate::outbound::OutboundHint {
            scope: crate::outbound::OutboundScope::Global,
            class: crate::outbound::OutboundClass::new(crate::outbound::class::OTHER),
            priority: crate::outbound::OutboundPriority::NORMAL,
            weight: std::num::NonZeroU32::new(1).unwrap(),
        }
    }
}
