//! Generated by `codegen_payloads`, do not edit by hand.

use serde::Serialize;

use crate::types::{InputProfilePhoto, True};

impl_payload! {
    @[multipart = photo]
    /// Changes the profile photo of the bot. Returns _True_ on success.
    #[derive(Debug, Clone, Serialize)]
    pub SetMyProfilePhoto (SetMyProfilePhotoSetters) => True {
        required {
            /// The new profile photo to set
            pub photo: InputProfilePhoto,
        }
    }
}

impl crate::outbound::OutboundPayload for SetMyProfilePhoto {
    fn outbound_hint(&self) -> crate::outbound::OutboundHint {
        crate::outbound::OutboundHint {
            scope: crate::outbound::OutboundScope::Global,
            class: crate::outbound::OutboundClass::new(crate::outbound::class::OTHER),
            priority: crate::outbound::OutboundPriority::NORMAL,
            weight: std::num::NonZeroU32::new(1).unwrap(),
        }
    }
}
