//! Generated by `codegen_payloads`, do not edit by hand.

use serde::Serialize;

use crate::types::True;

impl_payload! {
    /// Use this method to change the bot's name. Returns True on success.
    #[derive(Debug, PartialEq, Eq, Hash, Default, Clone, Serialize)]
    pub SetMyName (SetMyNameSetters) => True {
        optional {
            /// New bot name; 0-64 characters. Pass an empty string to remove the dedicated name for the given language.
            pub name: String [into],
            /// A two-letter ISO 639-1 language code. If empty, the name will be shown to all users for whose language there is no dedicated name.
            pub language_code: String [into],
        }
    }
}

impl crate::outbound::OutboundPayload for SetMyName {
    fn outbound_hint(&self) -> crate::outbound::OutboundHint {
        crate::outbound::OutboundHint {
            scope: crate::outbound::OutboundScope::Global,
            class: crate::outbound::OutboundClass::new(crate::outbound::class::OTHER),
            priority: crate::outbound::OutboundPriority::NORMAL,
            weight: std::num::NonZeroU32::new(1).unwrap(),
        }
    }
}
