//! Generated by `codegen_payloads`, do not edit by hand.

use serde::Serialize;

use crate::types::{Message, MessageId, UserId};

impl_payload! {
    /// Use this method to set the score of the specified user in a game. On success, returns the edited [`Message`]. Returns an error, if the new score is not greater than the user's current score in the chat and force is False.
    ///
    /// See also: [`SetGameScoreInline`](crate::payloads::SetGameScoreInline)
    ///
    /// [`Message`]: crate::types::Message
    #[derive(Debug, PartialEq, Eq, Hash, Clone, Serialize)]
    pub SetGameScore (SetGameScoreSetters) => Message {
        required {
            /// User identifier
            pub user_id: UserId,
            /// New score
            pub score: u64,
            /// Unique identifier for the target chat
            pub chat_id: u32,
            /// Identifier of the message to edit
            #[serde(flatten)]
            pub message_id: MessageId,
        }
        optional {
            /// Pass True, if the high score is allowed to decrease. This can be useful when fixing mistakes or banning cheaters
            pub force: bool,
            /// Pass True, if the game message should not be automatically edited to include the current scoreboard
            pub disable_edit_message: bool,
        }
    }
}

impl crate::outbound::OutboundPayload for SetGameScore {
    fn outbound_hint(&self) -> crate::outbound::OutboundHint {
        crate::outbound::OutboundHint {
            scope: crate::outbound::classify::game_chat_id_scope(self.chat_id),
            class: crate::outbound::OutboundClass::new(crate::outbound::class::OTHER),
            priority: crate::outbound::OutboundPriority::NORMAL,
            weight: std::num::NonZeroU32::new(1).unwrap(),
        }
    }
}
