//! Generated by `codegen_payloads`, do not edit by hand.

use serde::Serialize;

use crate::types::True;

impl_payload! {
    /// Use this method to change the bot's description, which is shown in the chat with the bot if the chat is empty. Returns True on success.
    #[derive(Debug, PartialEq, Eq, Hash, Default, Clone, Serialize)]
    pub SetMyDescription (SetMyDescriptionSetters) => True {
        optional {
            /// New bot description; 0-512 characters. Pass an empty string to remove the dedicated description for the given language.
            pub description: String [into],
            /// A two-letter ISO 639-1 language code. If empty, the description will be applied to all users for whose language there is no dedicated description.
            pub language_code: String [into],
        }
    }
}

impl crate::outbound::OutboundPayload for SetMyDescription {
    fn outbound_hint(&self) -> crate::outbound::OutboundHint {
        crate::outbound::OutboundHint {
            scope: crate::outbound::OutboundScope::Global,
            class: crate::outbound::OutboundClass::new(crate::outbound::class::OTHER),
            priority: crate::outbound::OutboundPriority::NORMAL,
            weight: std::num::NonZeroU32::new(1).unwrap(),
        }
    }
}
