//! Generated by `codegen_payloads`, do not edit by hand.

use serde::Serialize;

use crate::types::{BotCommand, BotCommandScope, True};

impl_payload! {
    /// Use this method to change the list of the bot's commands. Returns _True_ on success.
    #[derive(Debug, PartialEq, Eq, Hash, Clone, Serialize)]
    pub SetMyCommands (SetMyCommandsSetters) => True {
        required {
            /// A JSON-serialized list of bot commands to be set as the list of the bot's commands. At most 100 commands can be specified.
            pub commands: Vec<BotCommand> [collect],
        }
        optional {
            /// A JSON-serialized object, describing scope of users for which the commands are relevant. Defaults to BotCommandScopeDefault.
            pub scope: BotCommandScope,
            /// A two-letter ISO 639-1 language code. If empty, commands will be applied to all users from the given scope, for whose language there are no dedicated commands
            pub language_code: String [into],
        }
    }
}

impl crate::outbound::OutboundPayload for SetMyCommands {
    fn outbound_hint(&self) -> crate::outbound::OutboundHint {
        crate::outbound::OutboundHint {
            scope: crate::outbound::OutboundScope::Global,
            class: crate::outbound::OutboundClass::new(crate::outbound::class::OTHER),
            priority: crate::outbound::OutboundPriority::NORMAL,
            weight: std::num::NonZeroU32::new(1).unwrap(),
        }
    }
}
