//! Generated by `codegen_payloads`, do not edit by hand.

use serde::Serialize;

use crate::types::True;

impl_payload! {
    /// Use this method to change the list of emoji assigned to a regular or custom emoji sticker. The sticker must belong to a sticker set created by the bot. Returns True on success.
    #[derive(Debug, PartialEq, Eq, Hash, Clone, Serialize)]
    pub SetStickerEmojiList (SetStickerEmojiListSetters) => True {
        required {
            /// File identifier of the sticker
            pub sticker: String [into],
            /// A JSON-serialized list of 1-20 emoji associated with the sticker
            pub emoji_list: Vec<String> [collect],
        }
    }
}

impl crate::outbound::OutboundPayload for SetStickerEmojiList {
    fn outbound_hint(&self) -> crate::outbound::OutboundHint {
        crate::outbound::OutboundHint {
            scope: crate::outbound::OutboundScope::Global,
            class: crate::outbound::OutboundClass::new(crate::outbound::class::OTHER),
            priority: crate::outbound::OutboundPriority::NORMAL,
            weight: std::num::NonZeroU32::new(1).unwrap(),
        }
    }
}
