//! Generated by `codegen_payloads`, do not edit by hand.

use serde::Serialize;

use crate::types::{BusinessConnectionId, ChatId, OwnedGiftId, True};

impl_payload! {
    /// Transfers an owned unique gift to another user. Requires the _can_transfer_and_upgrade_gifts_ business bot right. Requires _can_transfer_stars_ business bot right if the transfer is paid. Returns _true_ on success.
    #[derive(Debug, PartialEq, Eq, Hash, Clone, Serialize)]
    pub TransferGift (TransferGiftSetters) => True {
        required {
            /// Unique identifier of the business connection
            pub business_connection_id: BusinessConnectionId,
            /// Unique identifier of the regular gift that should be converted to Telegram Stars
            pub owned_gift_id: OwnedGiftId,
            /// Unique identifier of the chat which will own the gift. The chat must be active in the last 24 hours
            pub new_owner_chat_id: ChatId [into],
        }
        optional {
            /// The amount of Telegram Stars that will be paid for the transfer from the business account balance. If positive, then the _can_transfer_stars_ business bot right is required
            pub star_count: u32,
        }
    }
}

impl crate::outbound::OutboundPayload for TransferGift {
    fn outbound_hint(&self) -> crate::outbound::OutboundHint {
        crate::outbound::OutboundHint {
            scope: crate::outbound::classify::new_owner_chat_id_scope(&self.new_owner_chat_id),
            class: crate::outbound::OutboundClass::new(crate::outbound::class::OTHER),
            priority: crate::outbound::OutboundPriority::NORMAL,
            weight: std::num::NonZeroU32::new(1).unwrap(),
        }
    }
}
