//! Generated by `codegen_payloads`, do not edit by hand.

use serde::Serialize;

use crate::types::{ChatId, Recipient, True};

impl_payload! {
    /// Use this method to unban a previously banned channel chat in a supergroup or channel. The bot must be an administrator for this to work and must have the appropriate administrator rights.
    #[derive(Debug, PartialEq, Eq, Hash, Clone, Serialize)]
    pub UnbanChatSenderChat (UnbanChatSenderChatSetters) => True {
        required {
            /// Unique identifier for the target chat or username of the target channel (in the format `@channelusername`)
            pub chat_id: Recipient [into],
            /// Unique identifier of the target sender chat
            pub sender_chat_id: ChatId [into],
        }
    }
}

impl crate::outbound::OutboundPayload for UnbanChatSenderChat {
    fn outbound_hint(&self) -> crate::outbound::OutboundHint {
        crate::outbound::OutboundHint {
            scope: crate::outbound::classify::scope_of_recipient(&self.chat_id),
            class: crate::outbound::OutboundClass::new(crate::outbound::class::OTHER),
            priority: crate::outbound::OutboundPriority::NORMAL,
            weight: std::num::NonZeroU32::new(1).unwrap(),
        }
    }
}
