//! Generated by `codegen_payloads`, do not edit by hand.

use serde::Serialize;

use crate::types::{Recipient, True};

impl_payload! {
    /// Verifies a chat [on behalf of the organization] which is represented by the bot. Returns _true_ on success.
    ///
    /// [on behalf of the organization]: https://telegram.org/verify#third-party-verification
    #[derive(Debug, PartialEq, Eq, Hash, Clone, Serialize)]
    pub VerifyChat (VerifyChatSetters) => True {
        required {
            /// Unique identifier for the target chat or username of the target channel
            pub chat_id: Recipient [into],
        }
        optional {
            /// Custom description for the verification; 0-70 characters. Must be empty if the organization isn't allowed to provide a custom verification description.
            pub custom_description: String [into],
        }
    }
}

impl crate::outbound::OutboundPayload for VerifyChat {
    fn outbound_hint(&self) -> crate::outbound::OutboundHint {
        crate::outbound::OutboundHint {
            scope: crate::outbound::classify::scope_of_recipient(&self.chat_id),
            class: crate::outbound::OutboundClass::new(crate::outbound::class::OTHER),
            priority: crate::outbound::OutboundPriority::NORMAL,
            weight: std::num::NonZeroU32::new(1).unwrap(),
        }
    }
}
